### ISSUE TITLE
Stuck on "Unpacking papirus-icon-theme (20190203-1) over (20190203-1)"

### ISSUE THREAD

**Issue by Emppu45** [EXALAB/AnLinux-App#199]
I tried to install Lxqt desktop enviroment to Debian, it started installing normally until it was unpacking papirus icon theme. It got stuck to that point.
![Screenshot_20191227-190750](https://user-images.githubusercontent.com/38589882/71525822-34161500-28dc-11ea-99ce-298a2df466b0.png)

**Comment by rekhubs** [comment]
same here...

**Comment by GT-610** [comment]
It needs some time. I've also met this problem, however the unpacking will end around half an hour later.

**Comment by newflydd** [comment]
yes, it take me about 20 minutes.

**Comment by maxie7** [comment]
the same here!!!! 
`Unpacking papirus-icon-theme (20201101-1) over (20201201-1)`
it hangs the updates, && and I can do nothing. When I'm trying remove it , it says 'can't remove... blah blah, please reinstall it', and I can't reinstall it because the 1st step of reinstall is 'unpacking' which hangs the updates... and so on, indefinite iterations...
I tried 
`sudo apt-mark hold papirus-icon-theme`
for not updating this package but it doesn't permit to update another packages of the system.

**Comment by maxie7** [comment]
> yes, it take me about 20 minutes.

I was waiting for > an hour.

**Comment by Disert774** [comment]
Stuck on Setting up papirus-icon-theme (20220204-5755+pkg22~ubuntu20.04.1) ...

**Comment by louis-frayser** [comment]
Yep,  I hung for about 10 minutes or so, then all's well :)
papirus-icon-theme 20210901-1\~ubuntu20.04.1~ppa1

**Comment by zakiloki0** [comment]
Same issue, stuck forever.

**Comment by cubkegger** [comment]
Actually been on for hours and it's not passing... Pretty sure it's a bug. But not really any way to tell for sure.

**Comment by falkolab** [comment]
stuck unpacking papyrus-icon-theme doesn't mean stuck forever. depending on the speed of storage and device to unpack the .deb file

for me it stuck for 8 hours, and I finally canceled the installation. And it stuck again ...

**Comment by Kimphunh** [comment]
Brur i get stucking for 30 mins and it still dont have a change, it was 20 mins at first and get away i was pheuu... But IT APPEAR AGAIN 
I STILL FCKIN WAIT FOR IT
I NEED HELPPP

**Comment by Kimphunh** [comment]
> simple. dont use anlinux. find other alternative

Luckily, it gone
