### ISSUE TITLE
Screen Resolution

### ISSUE THREAD

**Issue by albcal** [EXALAB/AnLinux-App#25]
Hi !
How can I change the screen resolution to vnc server?
Setting the res on .vnc/xstartup dont work 
thankyou

**Comment by exalab999** [comment]
Hi,

Simply edit this file:

/usr/local/bin/vncserver-start


Regards, EXA Lab

On Nov 16, 2018 10:44 PM, "albcal" <notifications@github.com> wrote:

Hi !
How can I change the screen resolution to vnc server?
Setting the res on .vnc/xstartup dont work
thankyou

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/EXALAB/AnLinux-App/issues/25>, or mute the thread

**Comment by albcal** [comment]
it works ! thankyou and amazing work,  just one thing, is posible to create mounts?

**Comment by exalab999** [comment]
Yes, it is possible by editing the start-*.sh in Termux, there are options to mount sdcard too, you could also edit the file to suits your need.
