### ISSUE TITLE
enable debian-security by default in sources.list

### ISSUE THREAD

**Issue by jindam-vani** [EXALAB/AnLinux-App#403]
* i havent saved my sources.list but it seems debian 
security repo is missing?

* ideally i would have:

```
deb http://deb.debian.org/debian bullseye main contrib non-free
deb http://deb.debian.org/debian-security/ bullseye-security main contrib non-free

#deb-src http://deb.debian.org/debian bullseye main contrib non-free
#deb-src http://deb.debian.org/debian-security/ bullseye-security main contrib non-free
```

* wishlist:
```
deb http://deb.debian.org/debian bullseye main contrib non-free
deb http://deb.debian.org/debian-security/ bullseye-security main contrib non-free
deb http://deb.debian.org/debian bullseye-updates main contrib non-free
deb http://deb.debian.org/debian bullseye-backports main contrib non-free

#deb-src http://deb.debian.org/debian bullseye main contrib non-free
#deb-src http://deb.debian.org/debian-security/ bullseye-security main contrib non-free
#deb-src http://deb.debian.org/debian bullseye-updates main contrib non-free
#deb-src http://deb.debian.org/debian bullseye-backports main contrib non-free
```

**Comment by exalab999** [comment]
These will be added in the distro update today, along with Ubuntu sources.list update.

**Comment by exalab999** [comment]
@jindam-vani 

There's nothing rude in your words.

1. I think this issue is better labeled as bugs, thanks for the notify. The devs are aware of the default sources.list problems and are working to fix it in the next release, this is the developer's mistake, so no excuse here, however the security risk is minimized even without the security repo since the distro is running inside proot environment.
2. Yes, you are right, but we understand how the repo works.
3. **[These will be added in the distro update today, along with Ubuntu sources.list update.](https://github.com/EXALAB/AnLinux-App/issues/403#issuecomment-1312644756)** as stated above, the update and fix will be published later, thanks for your informing.
4. To Add up to this, this project is currently maintained at a 6 month life cycle (If no emergency bug occured).

**Comment by exalab999** [comment]
Yes, the new included security source in debian is:

`deb http://security.debian.org/debian-security bullseye-security main contrib non-free`

sources.list update apply as well for all apt based distro except Kali which including backports and a few other things.
