### ISSUE TITLE
Empty screen, only mouse cursor

### ISSUE THREAD

**Issue by darkoverlordofdata** [EXALAB/AnLinux-App#78]
So it took most of the day, but I finally deciphered the instructions. The copy button puts commands in the copy/paste buffer. Why don't you just say so?

And after all that, it still doesn't work. I connect via vnc, and I get a blank screen that only has a mouse cursor.

Iv'e gotten better results using this: [https://yadominjinta.github.io/2018/08/18/GUI-on-termux-EN.html](https://yadominjinta.github.io/2018/08/18/GUI-on-termux-EN.html), so I'll stop wasting time on this and continue on with Yodomin's cause it actually works.

**Comment by darkoverlordofdata** [comment]
Not worth wasting any more time on.

**Comment by exalab999** [comment]
@darkoverlordofdata 

First of all, you accurse people by saying an open source project is malware, then you say the instruction is not clearly.

**Step 3 Copy the command XXX**

and with a **COPY** button below, well, this is your comprehension problem anyway.

Second, Never a text in the app say you must install anything from the advertisement to use, how to you imagine that to happen?

The last thing is, currently there is no problem about the Desktop Environment script, even on Android 8.0+ which have restriction, how do you manage to get blank screen that only has a mouse cursor ?

Actually I am happy you go on another alternative now, if you have problem at first you could email us, there was a Bug Report in the app, but you don't use it to get support, all you do is posting 1 star review, accusing people, and nag like a kid just because you can't figure how it work.

If all you want is that, you can get lost now, no one cares.
